// @ts-nocheck
/**
 * Music / BGM (procedural chiptune). Implementation: ./engine.ts
 *
 * Readable public API + internal helpers used by the scheduler.
 */
export {
  // transport / volume
  bgmSetMaster,
  bgmSetMuted,
  bgmToggleMute,
  applyMasterGain,
  bgmSetBgmVol,
  bgmSetSfxVol,
  bgmIsMuted,
  bgmStartScene,
  bgmBoss,
  bgmStop,
  bgmUnlock,
  clearBgmTimer,
  playBgmForMode,
  soundCatalogMeta,
  getBossThemeMeta,
  bgmResume,
  scheduleNextTick,
  // readable aliases
  bgmSetMaster as unlockAudio,
  bgmSetMuted as setMuted,
  bgmToggleMute as toggleMute,
  bgmSetBgmVol as setMasterVol,
  bgmSetSfxVol as setBgmVol,
  bgmIsMuted as setSfxVol,
  bgmStartScene as startBgm,
  bgmBoss as startBossBgm,
  bgmStop as startLegacyBossBgm,
  bgmUnlock as stopBgm,
  clearBgmTimer as stopBgmScheduler,
  playBgmForMode as playSoundTestTrack,
  soundCatalogMeta as soundTestCatalog,
  getBossThemeMeta as getBossThemeCard,
} from "./engine";

// Internal patch / voice helpers (readable names after deobfuscation)
export {
  makeRng,
  makeChipPatch,
  makeBossPatch,
  bgmMode,
  CHIP_LEADS,
  activePatch,
  degreeToMidi,
  arpSteps,
  pickArpStep,
  drumKickLight,
  drumKick,
  drumSnare,
  drumHat,
  playBell,
  playDistorted,
  playSlide,
  playBrassFanfare,
  playChoirChord,
  playBassVowel,
  getNoiseBuffer,
  playFormant,
  playWhistleTone,
  playWhistleArp,
  playCanonLead,
  playCanonFollow,
  playOrganStack,
  playOrganPedal,
  playTriad,
  playPluck,
  playBrassNote,
  playDrums,
  mutateLeadLine,
  makeHarmonyPatch,
  makeWhistlePatch,
  makeCanonPatch,
  makeOrganPatch,
  makeFlavorPatch,
  makeDawnPatch,
  makeSubjectPatch,
  makeContinuoPatch,
  makeBellsPatch,
  makeChasePatch,
  makeSilencePatch,
  makeIronPatch,
  makeTearPatch,
  makeStormPatch,
  makeAbyssPatch,
  makeCadencePatch,
  themeSeed,
  bgmStage,
  tickIndex,
  tickTimer,
  CHIP_SCALES,
  CHIP_PROGS,
  noiseBufCache,
  // temporary short aliases for residual callers
  makeBellsPatch as A,
  playTriad as B,
  makeSubjectPatch as Be,
  CHIP_SCALES as Ce,
  getBossThemeMeta as D,
  makeChipPatch as De,
  CHIP_PROGS as Ee,
  degreeToMidi as F,
  makeHarmonyPatch as Fe,
  makeAbyssPatch as Ge,
  scheduleNextTick as H,
  makeIronPatch as He,
  drumKick as I,
  makeWhistlePatch as Ie,
  pickArpStep as Je,
  makeBossPatch as Ke,
  drumHat as L,
  makeOrganPatch as Le,
  makeSilencePatch as M,
  makeCadencePatch as N,
  activePatch as P,
  mutateLeadLine as Pe,
  playBrassFanfare as Qe,
  playDistorted as R,
  makeFlavorPatch as Re,
  tickTimer as Se,
  bgmMode as T,
  CHIP_LEADS as Te,
  clearBgmTimer as U,
  makeTearPatch as Ue,
  playPluck as V,
  makeContinuoPatch as Ve,
  makeStormPatch as We,
  drumSnare as Xe,
  drumKickLight as Ye,
  playBell as Ze,
  playWhistleTone as at,
  bgmStage as be,
  playCanonFollow as ct,
  playBrassNote as dt,
  playChoirChord as et,
  playDrums as ft,
  playFormant as it,
  makeChasePatch as j,
  makeCanonPatch as k,
  playOrganStack as lt,
  noiseBufCache as nt,
  playWhistleArp as ot,
  arpSteps as qe,
  getNoiseBuffer as rt,
  playCanonLead as st,
  playBassVowel as tt,
  playOrganPedal as ut,
  makeRng as we,
  tickIndex as xe,
  applyMasterGain as y,
  themeSeed as ye,
  playSlide as z,
  makeDawnPatch as ze,
} from "./engine";
