/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BannerRouteImport } from './routes/banner'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PartnerRouteImport } from './routes/partner'
import { Route as TitleBgmRouteImport } from './routes/title-bgm'
import { Route as ApiAccountLinkRouteImport } from './routes/api/account/link'
import { Route as ApiAccountProfileRouteImport } from './routes/api/account/profile'
import { Route as ApiAdminPromoRouteImport } from './routes/api/admin/promo'
import { Route as ApiAdminStaffRouteImport } from './routes/api/admin/staff'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiPromoClaimRouteImport } from './routes/api/promo/claim'
import { Route as ApiRtcRouteImport } from './routes/api/rtc'
import { Route as ApiShareAwardRouteImport } from './routes/api/share/award'
import { Route as ApiShareBalanceRouteImport } from './routes/api/share/balance'
import { Route as ApiShareMediaCatalogRouteImport } from './routes/api/share/media-catalog'
import { Route as ApiShareMediaWatchRouteImport } from './routes/api/share/media-watch'
import { Route as ApiShareMessageRouteImport } from './routes/api/share/message'
import { Route as ApiShareMissionRouteImport } from './routes/api/share/mission'
import { Route as ApiSharePartnerRouteImport } from './routes/api/share/partner'
import { Route as ApiSharePartnerBannerRouteImport } from './routes/api/share/partner-banner'
import { Route as ApiSharePartnerCreditRouteImport } from './routes/api/share/partner-credit'
import { Route as ApiShareSpendRouteImport } from './routes/api/share/spend'
import { Route as ApiShareStripPresetsRouteImport } from './routes/api/share/strip-presets'
import { Route as ApiShareSyncRouteImport } from './routes/api/share/sync'
import { Route as ApiShareYoutubeMetaRouteImport } from './routes/api/share/youtube-meta'
import { Route as ApiSoundCommentsRouteImport } from './routes/api/sound/comments'
import { Route as ApiSoundUrlReportRouteImport } from './routes/api/sound/url-report'
import { Route as ApiSoundUrlVisitRouteImport } from './routes/api/sound/url-visit'
import { Route as ApiSoundVotesRouteImport } from './routes/api/sound/votes'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BannerRoute = BannerRouteImport.update({
  id: '/banner',
  path: '/banner',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerRoute = PartnerRouteImport.update({
  id: '/partner',
  path: '/partner',
  getParentRoute: () => rootRouteImport,
} as any)
const TitleBgmRoute = TitleBgmRouteImport.update({
  id: '/title-bgm',
  path: '/title-bgm',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAccountLinkRoute = ApiAccountLinkRouteImport.update({
  id: '/api/account/link',
  path: '/api/account/link',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAccountProfileRoute = ApiAccountProfileRouteImport.update({
  id: '/api/account/profile',
  path: '/api/account/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminPromoRoute = ApiAdminPromoRouteImport.update({
  id: '/api/admin/promo',
  path: '/api/admin/promo',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminStaffRoute = ApiAdminStaffRouteImport.update({
  id: '/api/admin/staff',
  path: '/api/admin/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPromoClaimRoute = ApiPromoClaimRouteImport.update({
  id: '/api/promo/claim',
  path: '/api/promo/claim',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRtcRoute = ApiRtcRouteImport.update({
  id: '/api/rtc',
  path: '/api/rtc',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiShareAwardRoute = ApiShareAwardRouteImport.update({
  id: '/api/share/award',
  path: '/api/share/award',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiShareBalanceRoute = ApiShareBalanceRouteImport.update({
  id: '/api/share/balance',
  path: '/api/share/balance',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiShareMediaCatalogRoute = ApiShareMediaCatalogRouteImport.update({
  id: '/api/share/media-catalog',
  path: '/api/share/media-catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiShareMediaWatchRoute = ApiShareMediaWatchRouteImport.update({
  id: '/api/share/media-watch',
  path: '/api/share/media-watch',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiShareMessageRoute = ApiShareMessageRouteImport.update({
  id: '/api/share/message',
  path: '/api/share/message',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiShareMissionRoute = ApiShareMissionRouteImport.update({
  id: '/api/share/mission',
  path: '/api/share/mission',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSharePartnerRoute = ApiSharePartnerRouteImport.update({
  id: '/api/share/partner',
  path: '/api/share/partner',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSharePartnerBannerRoute = ApiSharePartnerBannerRouteImport.update({
  id: '/api/share/partner-banner',
  path: '/api/share/partner-banner',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSharePartnerCreditRoute = ApiSharePartnerCreditRouteImport.update({
  id: '/api/share/partner-credit',
  path: '/api/share/partner-credit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiShareSpendRoute = ApiShareSpendRouteImport.update({
  id: '/api/share/spend',
  path: '/api/share/spend',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiShareStripPresetsRoute = ApiShareStripPresetsRouteImport.update({
  id: '/api/share/strip-presets',
  path: '/api/share/strip-presets',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiShareSyncRoute = ApiShareSyncRouteImport.update({
  id: '/api/share/sync',
  path: '/api/share/sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiShareYoutubeMetaRoute = ApiShareYoutubeMetaRouteImport.update({
  id: '/api/share/youtube-meta',
  path: '/api/share/youtube-meta',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSoundCommentsRoute = ApiSoundCommentsRouteImport.update({
  id: '/api/sound/comments',
  path: '/api/sound/comments',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSoundUrlReportRoute = ApiSoundUrlReportRouteImport.update({
  id: '/api/sound/url-report',
  path: '/api/sound/url-report',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSoundUrlVisitRoute = ApiSoundUrlVisitRouteImport.update({
  id: '/api/sound/url-visit',
  path: '/api/sound/url-visit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSoundVotesRoute = ApiSoundVotesRouteImport.update({
  id: '/api/sound/votes',
  path: '/api/sound/votes',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/banner': typeof BannerRoute
  '/login': typeof LoginRoute
  '/partner': typeof PartnerRoute
  '/title-bgm': typeof TitleBgmRoute
  '/api/account/link': typeof ApiAccountLinkRoute
  '/api/account/profile': typeof ApiAccountProfileRoute
  '/api/admin/promo': typeof ApiAdminPromoRoute
  '/api/admin/staff': typeof ApiAdminStaffRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/promo/claim': typeof ApiPromoClaimRoute
  '/api/rtc': typeof ApiRtcRoute
  '/api/share/award': typeof ApiShareAwardRoute
  '/api/share/balance': typeof ApiShareBalanceRoute
  '/api/share/media-catalog': typeof ApiShareMediaCatalogRoute
  '/api/share/media-watch': typeof ApiShareMediaWatchRoute
  '/api/share/message': typeof ApiShareMessageRoute
  '/api/share/mission': typeof ApiShareMissionRoute
  '/api/share/partner': typeof ApiSharePartnerRoute
  '/api/share/partner-banner': typeof ApiSharePartnerBannerRoute
  '/api/share/partner-credit': typeof ApiSharePartnerCreditRoute
  '/api/share/spend': typeof ApiShareSpendRoute
  '/api/share/strip-presets': typeof ApiShareStripPresetsRoute
  '/api/share/sync': typeof ApiShareSyncRoute
  '/api/share/youtube-meta': typeof ApiShareYoutubeMetaRoute
  '/api/sound/comments': typeof ApiSoundCommentsRoute
  '/api/sound/url-report': typeof ApiSoundUrlReportRoute
  '/api/sound/url-visit': typeof ApiSoundUrlVisitRoute
  '/api/sound/votes': typeof ApiSoundVotesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/banner': typeof BannerRoute
  '/login': typeof LoginRoute
  '/partner': typeof PartnerRoute
  '/title-bgm': typeof TitleBgmRoute
  '/api/account/link': typeof ApiAccountLinkRoute
  '/api/account/profile': typeof ApiAccountProfileRoute
  '/api/admin/promo': typeof ApiAdminPromoRoute
  '/api/admin/staff': typeof ApiAdminStaffRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/promo/claim': typeof ApiPromoClaimRoute
  '/api/rtc': typeof ApiRtcRoute
  '/api/share/award': typeof ApiShareAwardRoute
  '/api/share/balance': typeof ApiShareBalanceRoute
  '/api/share/media-catalog': typeof ApiShareMediaCatalogRoute
  '/api/share/media-watch': typeof ApiShareMediaWatchRoute
  '/api/share/message': typeof ApiShareMessageRoute
  '/api/share/mission': typeof ApiShareMissionRoute
  '/api/share/partner': typeof ApiSharePartnerRoute
  '/api/share/partner-banner': typeof ApiSharePartnerBannerRoute
  '/api/share/partner-credit': typeof ApiSharePartnerCreditRoute
  '/api/share/spend': typeof ApiShareSpendRoute
  '/api/share/strip-presets': typeof ApiShareStripPresetsRoute
  '/api/share/sync': typeof ApiShareSyncRoute
  '/api/share/youtube-meta': typeof ApiShareYoutubeMetaRoute
  '/api/sound/comments': typeof ApiSoundCommentsRoute
  '/api/sound/url-report': typeof ApiSoundUrlReportRoute
  '/api/sound/url-visit': typeof ApiSoundUrlVisitRoute
  '/api/sound/votes': typeof ApiSoundVotesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/banner': typeof BannerRoute
  '/login': typeof LoginRoute
  '/partner': typeof PartnerRoute
  '/title-bgm': typeof TitleBgmRoute
  '/api/account/link': typeof ApiAccountLinkRoute
  '/api/account/profile': typeof ApiAccountProfileRoute
  '/api/admin/promo': typeof ApiAdminPromoRoute
  '/api/admin/staff': typeof ApiAdminStaffRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/promo/claim': typeof ApiPromoClaimRoute
  '/api/rtc': typeof ApiRtcRoute
  '/api/share/award': typeof ApiShareAwardRoute
  '/api/share/balance': typeof ApiShareBalanceRoute
  '/api/share/media-catalog': typeof ApiShareMediaCatalogRoute
  '/api/share/media-watch': typeof ApiShareMediaWatchRoute
  '/api/share/message': typeof ApiShareMessageRoute
  '/api/share/mission': typeof ApiShareMissionRoute
  '/api/share/partner': typeof ApiSharePartnerRoute
  '/api/share/partner-banner': typeof ApiSharePartnerBannerRoute
  '/api/share/partner-credit': typeof ApiSharePartnerCreditRoute
  '/api/share/spend': typeof ApiShareSpendRoute
  '/api/share/strip-presets': typeof ApiShareStripPresetsRoute
  '/api/share/sync': typeof ApiShareSyncRoute
  '/api/share/youtube-meta': typeof ApiShareYoutubeMetaRoute
  '/api/sound/comments': typeof ApiSoundCommentsRoute
  '/api/sound/url-report': typeof ApiSoundUrlReportRoute
  '/api/sound/url-visit': typeof ApiSoundUrlVisitRoute
  '/api/sound/votes': typeof ApiSoundVotesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/banner'
    | '/login'
    | '/partner'
    | '/title-bgm'
    | '/api/account/link'
    | '/api/account/profile'
    | '/api/admin/promo'
    | '/api/admin/staff'
    | '/api/auth/$'
    | '/api/promo/claim'
    | '/api/rtc'
    | '/api/share/award'
    | '/api/share/balance'
    | '/api/share/media-catalog'
    | '/api/share/media-watch'
    | '/api/share/message'
    | '/api/share/mission'
    | '/api/share/partner'
    | '/api/share/partner-banner'
    | '/api/share/partner-credit'
    | '/api/share/spend'
    | '/api/share/strip-presets'
    | '/api/share/sync'
    | '/api/share/youtube-meta'
    | '/api/sound/comments'
    | '/api/sound/url-report'
    | '/api/sound/url-visit'
    | '/api/sound/votes'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/banner'
    | '/login'
    | '/partner'
    | '/title-bgm'
    | '/api/account/link'
    | '/api/account/profile'
    | '/api/admin/promo'
    | '/api/admin/staff'
    | '/api/auth/$'
    | '/api/promo/claim'
    | '/api/rtc'
    | '/api/share/award'
    | '/api/share/balance'
    | '/api/share/media-catalog'
    | '/api/share/media-watch'
    | '/api/share/message'
    | '/api/share/mission'
    | '/api/share/partner'
    | '/api/share/partner-banner'
    | '/api/share/partner-credit'
    | '/api/share/spend'
    | '/api/share/strip-presets'
    | '/api/share/sync'
    | '/api/share/youtube-meta'
    | '/api/sound/comments'
    | '/api/sound/url-report'
    | '/api/sound/url-visit'
    | '/api/sound/votes'
  id:
    | '__root__'
    | '/'
    | '/banner'
    | '/login'
    | '/partner'
    | '/title-bgm'
    | '/api/account/link'
    | '/api/account/profile'
    | '/api/admin/promo'
    | '/api/admin/staff'
    | '/api/auth/$'
    | '/api/promo/claim'
    | '/api/rtc'
    | '/api/share/award'
    | '/api/share/balance'
    | '/api/share/media-catalog'
    | '/api/share/media-watch'
    | '/api/share/message'
    | '/api/share/mission'
    | '/api/share/partner'
    | '/api/share/partner-banner'
    | '/api/share/partner-credit'
    | '/api/share/spend'
    | '/api/share/strip-presets'
    | '/api/share/sync'
    | '/api/share/youtube-meta'
    | '/api/sound/comments'
    | '/api/sound/url-report'
    | '/api/sound/url-visit'
    | '/api/sound/votes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BannerRoute: typeof BannerRoute
  LoginRoute: typeof LoginRoute
  PartnerRoute: typeof PartnerRoute
  TitleBgmRoute: typeof TitleBgmRoute
  ApiAccountLinkRoute: typeof ApiAccountLinkRoute
  ApiAccountProfileRoute: typeof ApiAccountProfileRoute
  ApiAdminPromoRoute: typeof ApiAdminPromoRoute
  ApiAdminStaffRoute: typeof ApiAdminStaffRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiPromoClaimRoute: typeof ApiPromoClaimRoute
  ApiRtcRoute: typeof ApiRtcRoute
  ApiShareAwardRoute: typeof ApiShareAwardRoute
  ApiShareBalanceRoute: typeof ApiShareBalanceRoute
  ApiShareMediaCatalogRoute: typeof ApiShareMediaCatalogRoute
  ApiShareMediaWatchRoute: typeof ApiShareMediaWatchRoute
  ApiShareMessageRoute: typeof ApiShareMessageRoute
  ApiShareMissionRoute: typeof ApiShareMissionRoute
  ApiSharePartnerRoute: typeof ApiSharePartnerRoute
  ApiSharePartnerBannerRoute: typeof ApiSharePartnerBannerRoute
  ApiSharePartnerCreditRoute: typeof ApiSharePartnerCreditRoute
  ApiShareSpendRoute: typeof ApiShareSpendRoute
  ApiShareStripPresetsRoute: typeof ApiShareStripPresetsRoute
  ApiShareSyncRoute: typeof ApiShareSyncRoute
  ApiShareYoutubeMetaRoute: typeof ApiShareYoutubeMetaRoute
  ApiSoundCommentsRoute: typeof ApiSoundCommentsRoute
  ApiSoundUrlReportRoute: typeof ApiSoundUrlReportRoute
  ApiSoundUrlVisitRoute: typeof ApiSoundUrlVisitRoute
  ApiSoundVotesRoute: typeof ApiSoundVotesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/banner': {
      id: '/banner'
      path: '/banner'
      fullPath: '/banner'
      preLoaderRoute: typeof BannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner': {
      id: '/partner'
      path: '/partner'
      fullPath: '/partner'
      preLoaderRoute: typeof PartnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/title-bgm': {
      id: '/title-bgm'
      path: '/title-bgm'
      fullPath: '/title-bgm'
      preLoaderRoute: typeof TitleBgmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/account/link': {
      id: '/api/account/link'
      path: '/api/account/link'
      fullPath: '/api/account/link'
      preLoaderRoute: typeof ApiAccountLinkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/account/profile': {
      id: '/api/account/profile'
      path: '/api/account/profile'
      fullPath: '/api/account/profile'
      preLoaderRoute: typeof ApiAccountProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/promo': {
      id: '/api/admin/promo'
      path: '/api/admin/promo'
      fullPath: '/api/admin/promo'
      preLoaderRoute: typeof ApiAdminPromoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/staff': {
      id: '/api/admin/staff'
      path: '/api/admin/staff'
      fullPath: '/api/admin/staff'
      preLoaderRoute: typeof ApiAdminStaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/promo/claim': {
      id: '/api/promo/claim'
      path: '/api/promo/claim'
      fullPath: '/api/promo/claim'
      preLoaderRoute: typeof ApiPromoClaimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rtc': {
      id: '/api/rtc'
      path: '/api/rtc'
      fullPath: '/api/rtc'
      preLoaderRoute: typeof ApiRtcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/share/award': {
      id: '/api/share/award'
      path: '/api/share/award'
      fullPath: '/api/share/award'
      preLoaderRoute: typeof ApiShareAwardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/share/balance': {
      id: '/api/share/balance'
      path: '/api/share/balance'
      fullPath: '/api/share/balance'
      preLoaderRoute: typeof ApiShareBalanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/share/media-catalog': {
      id: '/api/share/media-catalog'
      path: '/api/share/media-catalog'
      fullPath: '/api/share/media-catalog'
      preLoaderRoute: typeof ApiShareMediaCatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/share/media-watch': {
      id: '/api/share/media-watch'
      path: '/api/share/media-watch'
      fullPath: '/api/share/media-watch'
      preLoaderRoute: typeof ApiShareMediaWatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/share/message': {
      id: '/api/share/message'
      path: '/api/share/message'
      fullPath: '/api/share/message'
      preLoaderRoute: typeof ApiShareMessageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/share/mission': {
      id: '/api/share/mission'
      path: '/api/share/mission'
      fullPath: '/api/share/mission'
      preLoaderRoute: typeof ApiShareMissionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/share/partner': {
      id: '/api/share/partner'
      path: '/api/share/partner'
      fullPath: '/api/share/partner'
      preLoaderRoute: typeof ApiSharePartnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/share/partner-banner': {
      id: '/api/share/partner-banner'
      path: '/api/share/partner-banner'
      fullPath: '/api/share/partner-banner'
      preLoaderRoute: typeof ApiSharePartnerBannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/share/partner-credit': {
      id: '/api/share/partner-credit'
      path: '/api/share/partner-credit'
      fullPath: '/api/share/partner-credit'
      preLoaderRoute: typeof ApiSharePartnerCreditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/share/spend': {
      id: '/api/share/spend'
      path: '/api/share/spend'
      fullPath: '/api/share/spend'
      preLoaderRoute: typeof ApiShareSpendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/share/strip-presets': {
      id: '/api/share/strip-presets'
      path: '/api/share/strip-presets'
      fullPath: '/api/share/strip-presets'
      preLoaderRoute: typeof ApiShareStripPresetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/share/sync': {
      id: '/api/share/sync'
      path: '/api/share/sync'
      fullPath: '/api/share/sync'
      preLoaderRoute: typeof ApiShareSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/share/youtube-meta': {
      id: '/api/share/youtube-meta'
      path: '/api/share/youtube-meta'
      fullPath: '/api/share/youtube-meta'
      preLoaderRoute: typeof ApiShareYoutubeMetaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sound/comments': {
      id: '/api/sound/comments'
      path: '/api/sound/comments'
      fullPath: '/api/sound/comments'
      preLoaderRoute: typeof ApiSoundCommentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sound/url-report': {
      id: '/api/sound/url-report'
      path: '/api/sound/url-report'
      fullPath: '/api/sound/url-report'
      preLoaderRoute: typeof ApiSoundUrlReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sound/url-visit': {
      id: '/api/sound/url-visit'
      path: '/api/sound/url-visit'
      fullPath: '/api/sound/url-visit'
      preLoaderRoute: typeof ApiSoundUrlVisitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sound/votes': {
      id: '/api/sound/votes'
      path: '/api/sound/votes'
      fullPath: '/api/sound/votes'
      preLoaderRoute: typeof ApiSoundVotesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BannerRoute: BannerRoute,
  LoginRoute: LoginRoute,
  PartnerRoute: PartnerRoute,
  TitleBgmRoute: TitleBgmRoute,
  ApiAccountLinkRoute: ApiAccountLinkRoute,
  ApiAccountProfileRoute: ApiAccountProfileRoute,
  ApiAdminPromoRoute: ApiAdminPromoRoute,
  ApiAdminStaffRoute: ApiAdminStaffRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiPromoClaimRoute: ApiPromoClaimRoute,
  ApiRtcRoute: ApiRtcRoute,
  ApiShareAwardRoute: ApiShareAwardRoute,
  ApiShareBalanceRoute: ApiShareBalanceRoute,
  ApiShareMediaCatalogRoute: ApiShareMediaCatalogRoute,
  ApiShareMediaWatchRoute: ApiShareMediaWatchRoute,
  ApiShareMessageRoute: ApiShareMessageRoute,
  ApiShareMissionRoute: ApiShareMissionRoute,
  ApiSharePartnerRoute: ApiSharePartnerRoute,
  ApiSharePartnerBannerRoute: ApiSharePartnerBannerRoute,
  ApiSharePartnerCreditRoute: ApiSharePartnerCreditRoute,
  ApiShareSpendRoute: ApiShareSpendRoute,
  ApiShareStripPresetsRoute: ApiShareStripPresetsRoute,
  ApiShareSyncRoute: ApiShareSyncRoute,
  ApiShareYoutubeMetaRoute: ApiShareYoutubeMetaRoute,
  ApiSoundCommentsRoute: ApiSoundCommentsRoute,
  ApiSoundUrlReportRoute: ApiSoundUrlReportRoute,
  ApiSoundUrlVisitRoute: ApiSoundUrlVisitRoute,
  ApiSoundVotesRoute: ApiSoundVotesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
